package com.service_reservation.EAP03.modulos.admin.domain.model;

public enum AccionAdmin {
    SOLICITUD_PROVEEDOR_CREADA,
    SOLICITUD_PROVEEDOR_REENVIADA,
    SOLICITUD_PROVEEDOR_APROBADA,
    SOLICITUD_PROVEEDOR_RECHAZADA,
    REVOCACION_INICIADA,
    REVOCACION_COMPLETADA,
    REVOCACION_FORZADA,
    PERMISOS_RESTAURADOS,
    ACCESO_DENEGADO
}
