CREATE TABLE ROL (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE USUARIO (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    secret_2fa VARCHAR(255),
    is_2fa_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USUARIO_ROL (
    id_usuario BIGINT REFERENCES USUARIO(id), 
    id_rol BIGINT REFERENCES ROL(id),
    PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE CLIENTE (
    id BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT UNIQUE NOT NULL REFERENCES USUARIO(id),
    nombre VARCHAR(255) NOT NULL,
    telefono VARCHAR(50),
    documento VARCHAR(50)
);

CREATE TABLE PROVEEDOR (
    id BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT UNIQUE NOT NULL REFERENCES USUARIO(id),
    razon_social VARCHAR(255) NOT NULL,
    nit_rut VARCHAR(50),
    telefono VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ROL (nombre) VALUES ('CLIENTE'), ('PROVEEDOR');