-- Módulo: recursos (HU16 / tarea #41)
-- NOTA: id_proveedor e id_servicio_prestado se dejan sin restricción FOREIGN KEY
-- porque las tablas proveedor y servicio_prestado todavía no existen en la BD.
-- Pendiente: agregar esas FKs en una migración posterior cuando esas tablas existan.

CREATE TABLE recursos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor INTEGER NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_recursos_precio_unitario CHECK (precio_unitario >= 0),
    CONSTRAINT chk_recursos_stock CHECK (stock >= 0)
);

CREATE INDEX idx_recursos_id_proveedor ON recursos(id_proveedor);

CREATE TABLE recurso_prestado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recurso INTEGER NOT NULL,
    id_servicio_prestado INTEGER NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_total NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_recurso_prestado_recurso FOREIGN KEY (id_recurso) REFERENCES recursos(id) ON DELETE RESTRICT,
    CONSTRAINT chk_recurso_prestado_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_recurso_prestado_precio_total CHECK (precio_total >= 0)
);

CREATE INDEX idx_recurso_prestado_id_recurso ON recurso_prestado(id_recurso);
CREATE INDEX idx_recurso_prestado_id_servicio_prestado ON recurso_prestado(id_servicio_prestado);
