-- Módulo: recursos (HU16 / tarea #41)
-- DECISIÓN DE DISEÑO (permanente): id_proveedor e id_servicio_prestado se dejan como
-- enteros simples, sin FOREIGN KEY, porque pertenecen a otros módulos (auth y reservas
-- respectivamente). En esta arquitectura hexagonal modular, una tabla nunca lleva FK
-- hacia una tabla de otro módulo; solo se referencian tablas del propio módulo (ver
-- fk_recurso_prestado_recurso más abajo). La validación de que esos ids existan se hace
-- en la capa de aplicación, invocando el puerto expuesto por el módulo dueño de cada
-- tabla (auth para proveedor, reservas para servicio_prestado), no en la base de datos.

CREATE TABLE recurso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor INTEGER NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_recurso_precio_unitario CHECK (precio_unitario >= 0),
    CONSTRAINT chk_recurso_stock CHECK (stock >= 0)
);

CREATE INDEX idx_recurso_id_proveedor ON recurso(id_proveedor);

CREATE TABLE recurso_prestado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recurso INTEGER NOT NULL,
    id_servicio_prestado INTEGER NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_total NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_recurso_prestado_recurso FOREIGN KEY (id_recurso) REFERENCES recurso(id) ON DELETE RESTRICT,
    CONSTRAINT chk_recurso_prestado_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_recurso_prestado_precio_total CHECK (precio_total >= 0)
);

CREATE INDEX idx_recurso_prestado_id_recurso ON recurso_prestado(id_recurso);
CREATE INDEX idx_recurso_prestado_id_servicio_prestado ON recurso_prestado(id_servicio_prestado);
