-- Módulo: agendas_horarios (HU05)
-- DECISIÓN DE DISEÑO ARQUITECTURA HEXAGONAL:
-- Las columnas id_proveedor e id_servicio se definen como enteros simples, sin FOREIGN KEY,
-- porque corresponden a tablas de otros módulos (identidad y servicios_catalogo respectivamente).
-- Cada módulo es dueño de sus propias tablas y las validaciones de existencia se realizan
-- a través de los puertos de aplicación. Solo se establece FOREIGN KEY interna dentro del módulo
-- (fk_horario_agenda entre horario y agenda).

CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor INTEGER NOT NULL,
    id_servicio INTEGER NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_agenda_servicio_activa UNIQUE (id_servicio, activa)
);

CREATE INDEX idx_agenda_id_proveedor ON agenda(id_proveedor);

CREATE TABLE horario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agenda BIGINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    CONSTRAINT fk_horario_agenda FOREIGN KEY (id_agenda) REFERENCES agenda(id) ON DELETE CASCADE,
    CONSTRAINT chk_horario_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT chk_horario_dia_semana CHECK (dia_semana IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO'))
);

CREATE INDEX idx_horario_id_agenda ON horario(id_agenda);
