-- Módulo: admin (revocación / restauración de permisos operativos)
-- DECISIÓN DE DISEÑO ARQUITECTURA HEXAGONAL:
-- Siguiendo la convención del proyecto, las columnas id_usuario / id_admin / id_actor se
-- definen como enteros simples, sin FOREIGN KEY, porque USUARIO pertenece al módulo identidad.
-- Las validaciones de existencia se realizan a través de los puertos de aplicación.
--
-- Única excepción acordada: USUARIO_ROL (tabla de identidad) recibe la columna "activo", que
-- indica si el rol tiene permisos operativos. Tener el rol != poder operar con él.

-- 1. Permiso operativo por rol. Por defecto TRUE para no afectar a los usuarios existentes.
ALTER TABLE USUARIO_ROL ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;

-- 2. Solicitudes de aprobación de cuentas de proveedor
CREATE TABLE solicitud_aprobacion_proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL,
    fecha_resolucion TIMESTAMP,
    id_admin_resolutor BIGINT,
    motivo_rechazo VARCHAR(500),
    CONSTRAINT chk_solicitud_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

CREATE INDEX idx_solicitud_usuario ON solicitud_aprobacion_proveedor(id_usuario);
CREATE INDEX idx_solicitud_estado ON solicitud_aprobacion_proveedor(estado);

-- 3. Revocaciones de permisos operativos
--    PENDIENTE_CANCELACION: proveedor con reservas activas dentro del plazo de gracia (5 días)
--    COMPLETADA: revocación efectiva y cerrada
--    ANULADA: el admin restauró los permisos antes de completarse
CREATE TABLE revocacion_permiso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    rol VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    id_admin BIGINT NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL,
    fecha_limite TIMESTAMP,
    fecha_cierre TIMESTAMP,
    reservas_canceladas INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_revocacion_rol CHECK (rol IN ('CLIENTE', 'PROVEEDOR')),
    CONSTRAINT chk_revocacion_estado CHECK (estado IN ('PENDIENTE_CANCELACION', 'COMPLETADA', 'ANULADA'))
);

CREATE INDEX idx_revocacion_usuario_rol ON revocacion_permiso(id_usuario, rol);
CREATE INDEX idx_revocacion_estado ON revocacion_permiso(estado);

-- 4. Auditoría de acciones administrativas y de intentos de acceso denegados
CREATE TABLE admin_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    id_actor BIGINT,
    id_usuario_afectado BIGINT,
    accion VARCHAR(60) NOT NULL,
    rol VARCHAR(30),
    resultado VARCHAR(15) NOT NULL,
    endpoint VARCHAR(255),
    detalle VARCHAR(1000),
    CONSTRAINT chk_auditoria_resultado CHECK (resultado IN ('EXITO', 'DENEGADO'))
);

CREATE INDEX idx_auditoria_fecha ON admin_auditoria(fecha);
CREATE INDEX idx_auditoria_usuario_afectado ON admin_auditoria(id_usuario_afectado);

-- 5. Backfill: los proveedores existentes ya operaban, se registran como APROBADOS
--    (necesario para poder restaurarles permisos si en el futuro se les revocan).
INSERT INTO solicitud_aprobacion_proveedor (id_usuario, estado, fecha_solicitud, fecha_resolucion)
SELECT ur.id_usuario, 'APROBADA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM USUARIO_ROL ur
JOIN ROL r ON r.id = ur.id_rol
WHERE r.nombre = 'ROLE_PROVEEDOR';
